"""Pattern recognition module for chart patterns using ML"""

import numpy as np
import pandas as pd
from dataclasses import dataclass
from typing import Tuple, List
from scipy import signal
from config import PATTERN_CONFIG
from learned_pattern_detector import LearnedPatternDetector

@dataclass
class Pattern:
    """Detected pattern"""
    name: str
    confidence: float
    start_idx: int
    end_idx: int
    direction: str  # 'bullish' or 'bearish'
    breakout_price: float


class PatternRecognizer:
    """Detect technical patterns using ML-friendly feature extraction"""
    
    def __init__(self, learned_model_path: str = None):
        self.lookback = PATTERN_CONFIG['lookback_window']
        self.min_confidence = PATTERN_CONFIG['min_pattern_confidence']
        self.learned_model_path = learned_model_path
        self.learned_detector = LearnedPatternDetector(self.lookback, self.min_confidence)
        self.learned_enabled = False

        if self.learned_model_path:
            self.load_learned_detector(self.learned_model_path)

    def train_learned_detector(self, df: pd.DataFrame, max_samples: int = 3000, save_after_train: bool = True) -> bool:
        """Train learned detector using rule-labeled windows."""
        # Ensure labels are generated by the rule-based detector.
        self.learned_enabled = False
        trained = self.learned_detector.fit(
            df,
            self,
            max_samples=max_samples,
            forward_horizon=PATTERN_CONFIG.get('forward_horizon', 6),
            forward_return_threshold=PATTERN_CONFIG.get('forward_return_threshold', 0.0012),
        )
        self.learned_enabled = trained
        if trained and save_after_train and self.learned_model_path:
            self.save_learned_detector(self.learned_model_path)
        return trained

    def save_learned_detector(self, model_path: str = None) -> bool:
        """Save learned detector model to disk."""
        path = model_path or self.learned_model_path
        if not path or not self.learned_detector.is_trained:
            return False
        self.learned_detector.save(path)
        return True

    def load_learned_detector(self, model_path: str = None) -> bool:
        """Load learned detector model from disk."""
        path = model_path or self.learned_model_path
        if not path:
            return False
        loaded = self.learned_detector.load(path)
        self.learned_enabled = loaded
        return loaded

    def get_pattern_feature_vector(self, window: pd.DataFrame) -> np.ndarray:
        """Return compact pattern features (8 dims) for RL state."""
        if len(window) < self.lookback:
            return np.zeros(8, dtype=np.float32)

        if self.learned_enabled and self.learned_detector.is_trained:
            return self.learned_detector.feature_vector(window)

        patterns = self.detect_patterns(window)
        if not patterns:
            return np.zeros(8, dtype=np.float32)

        fallback = self.extract_pattern_features(patterns[-1], window)
        return fallback[:8].astype(np.float32)

    def detect_latest_pattern(self, window: pd.DataFrame) -> Pattern:
        """Return latest learned pattern when available, else fallback to rules."""
        if len(window) < self.lookback:
            return None

        if self.learned_enabled and self.learned_detector.is_trained:
            pred = self.learned_detector.predict(window)
            if pred.pattern_name != 'none' and pred.confidence >= self.min_confidence:
                breakout = window['high'].iloc[-1] if pred.direction == 'bullish' else window['low'].iloc[-1]
                return Pattern(
                    name=pred.pattern_name,
                    confidence=pred.confidence,
                    start_idx=max(0, len(window) - self.lookback),
                    end_idx=len(window),
                    direction=pred.direction,
                    breakout_price=breakout,
                )

        patterns = self.detect_patterns(window)
        return patterns[-1] if patterns else None
        
    def detect_patterns(self, df: pd.DataFrame) -> List[Pattern]:
        """
        Detect multiple patterns in price data.
        
        Args:
            df: DataFrame with OHLCV data
            
        Returns:
            List of Pattern objects
        """
        patterns = []
        
        for i in range(self.lookback, len(df)):
            window = df.iloc[i-self.lookback:i]
            
            # Try each pattern detection
            triangle = self._detect_triangle(window, i)
            if triangle:
                patterns.append(triangle)
            
            wedge = self._detect_wedge(window, i)
            if wedge:
                patterns.append(wedge)
            
            flag = self._detect_flag(window, i)
            if flag:
                patterns.append(flag)
            
            channel = self._detect_channel(window, i)
            if channel:
                patterns.append(channel)
            
            head_shoulders = self._detect_head_shoulders(window, i)
            if head_shoulders:
                patterns.append(head_shoulders)
        
        return patterns
    
    def _detect_triangle(self, window: pd.DataFrame, end_idx: int) -> Pattern:
        """Detect triangle consolidation pattern"""
        lows = window['low'].values
        highs = window['high'].values
        closes = window['close'].values
        
        # Triangle: converging high and low
        high_slope = self._calculate_slope(highs)
        low_slope = self._calculate_slope(lows)
        
        # Highs decreasing, lows increasing = converging
        if high_slope < -0.5 and low_slope > 0.5:
            convergence = abs(high_slope) + abs(low_slope)
            confidence = min(convergence / 2.0, 1.0)
            
            if confidence >= self.min_confidence:
                # Determine direction by close position
                close_ratio = (closes[-1] - lows[-1]) / (highs[-1] - lows[-1])
                direction = 'bullish' if close_ratio > 0.5 else 'bearish'
                breakout = highs[-1] if direction == 'bullish' else lows[-1]
                
                return Pattern(
                    name='triangle',
                    confidence=confidence,
                    start_idx=end_idx - len(window),
                    end_idx=end_idx,
                    direction=direction,
                    breakout_price=breakout
                )
        return None
    
    def _detect_wedge(self, window: pd.DataFrame, end_idx: int) -> Pattern:
        """Detect wedge pattern (rising or falling)"""
        lows = window['low'].values
        highs = window['high'].values
        
        high_slope = self._calculate_slope(highs)
        low_slope = self._calculate_slope(lows)
        
        # Rising wedge: both lines rising with highs rising faster
        if high_slope > 0.5 and low_slope > 0 and high_slope > low_slope + 0.5:
            confidence = min(high_slope / 2.0, 1.0)
            if confidence >= self.min_confidence:
                return Pattern(
                    name='wedge_rising',
                    confidence=confidence,
                    start_idx=end_idx - len(window),
                    end_idx=end_idx,
                    direction='bearish',  # Rising wedges typically break down
                    breakout_price=lows[-1]
                )
        
        # Falling wedge: both lines falling with lows falling faster
        if high_slope < -0.5 and low_slope < 0 and abs(low_slope) > abs(high_slope) + 0.5:
            confidence = min(abs(low_slope) / 2.0, 1.0)
            if confidence >= self.min_confidence:
                return Pattern(
                    name='wedge_falling',
                    confidence=confidence,
                    start_idx=end_idx - len(window),
                    end_idx=end_idx,
                    direction='bullish',  # Falling wedges typically break up
                    breakout_price=highs[-1]
                )
        
        return None
    
    def _detect_flag(self, window: pd.DataFrame, end_idx: int) -> Pattern:
        """Detect flag pattern (consolidation after strong move)"""
        closes = window['close'].values
        
        # Check for prior trend (flag pole)
        mid_point = len(closes) // 2
        early_change = abs(closes[mid_point] - closes[0]) / closes[0]
        late_change = abs(closes[-1] - closes[mid_point]) / closes[mid_point]
        
        # Strong prior move + consolidation
        if early_change > 0.02 and late_change < 0.01:
            direction = 'bullish' if closes[mid_point] > closes[0] else 'bearish'
            confidence = min(early_change, 1.0)
            
            if confidence >= self.min_confidence:
                breakout = window['high'].iloc[-1] if direction == 'bullish' else window['low'].iloc[-1]
                return Pattern(
                    name='flag',
                    confidence=confidence,
                    start_idx=end_idx - len(window),
                    end_idx=end_idx,
                    direction=direction,
                    breakout_price=breakout
                )
        
        return None
    
    def _detect_channel(self, window: pd.DataFrame, end_idx: int) -> Pattern:
        """Detect price channel (parallel support/resistance)"""
        highs = window['high'].values
        lows = window['low'].values
        
        high_slope = self._calculate_slope(highs)
        low_slope = self._calculate_slope(lows)
        
        # Parallel lines
        if abs(high_slope - low_slope) < 0.3:
            parallelism = 1.0 - abs(high_slope - low_slope)
            confidence = min(parallelism, 1.0)
            
            if confidence >= self.min_confidence:
                direction = 'bullish' if high_slope > 0 else 'bearish'
                return Pattern(
                    name='channel',
                    confidence=confidence,
                    start_idx=end_idx - len(window),
                    end_idx=end_idx,
                    direction=direction,
                    breakout_price=highs[-1] if direction == 'bullish' else lows[-1]
                )
        
        return None
    
    def _detect_head_shoulders(self, window: pd.DataFrame, end_idx: int) -> Pattern:
        """Detect head and shoulders pattern"""
        highs = window['high'].values
        
        if len(highs) < 5:
            return None
        
        # Find local peaks
        peaks = signal.argrelextrema(highs, np.greater, order=2)[0]
        
        if len(peaks) >= 3:
            # Check if middle peak is highest (head)
            left_shoulder = highs[peaks[0]]
            head = highs[peaks[1]]
            right_shoulder = highs[peaks[2]] if len(peaks) > 2 else highs[-1]
            
            # Head should be significantly higher
            if head > left_shoulder * 1.02 and head > right_shoulder * 1.02:
                confidence = min((head - max(left_shoulder, right_shoulder)) / head, 1.0)
                
                if confidence >= self.min_confidence:
                    return Pattern(
                        name='head_shoulders',
                        confidence=confidence,
                        start_idx=end_idx - len(window),
                        end_idx=end_idx,
                        direction='bearish',
                        breakout_price=min(left_shoulder, right_shoulder)
                    )
        
        return None
    
    def _calculate_slope(self, values: np.ndarray) -> float:
        """Calculate linear trend slope"""
        x = np.arange(len(values))
        z = np.polyfit(x, values, 1)
        return z[0]
    
    def extract_pattern_features(self, pattern: Pattern, df: pd.DataFrame) -> np.ndarray:
        """
        Extract numerical features from a detected pattern.
        
        Args:
            pattern: Pattern object
            df: Full DataFrame for context
            
        Returns:
            Feature vector for ML model
        """
        window = df.iloc[pattern.start_idx:pattern.end_idx]
        
        features = []
        
        # Pattern type (one-hot)
        pattern_types = ['triangle', 'wedge_rising', 'wedge_falling', 'flag', 'channel', 'head_shoulders']
        pattern_one_hot = [1 if pattern.name == pt else 0 for pt in pattern_types]
        features.extend(pattern_one_hot)
        
        # Confidence
        features.append(pattern.confidence)
        
        # Direction (1 for bullish, -1 for bearish)
        features.append(1 if pattern.direction == 'bullish' else -1)
        
        # Price action metrics
        close_prices = window['close'].values
        volatility = close_prices.std() / close_prices.mean()
        features.append(volatility)
        
        # Trend strength
        returns = np.diff(close_prices) / close_prices[:-1]
        trend_strength = np.mean(returns)
        features.append(trend_strength)
        
        # Volume trend
        volume = window['volume'].values
        if len(volume) > 1:
            volume_trend = volume[-1] / volume[0]
            features.append(volume_trend)
        else:
            features.append(1.0)
        
        return np.array(features)


if __name__ == '__main__':
    from data_provider import HFTDataProvider
    
    # Test pattern detection
    provider = HFTDataProvider()
    df = provider.get_historical_data('SPY', days=30)
    
    recognizer = PatternRecognizer()
    patterns = recognizer.detect_patterns(df)
    
    print(f"Detected {len(patterns)} patterns:")
    for p in patterns[-5:]:
        print(f"  {p.name}: {p.confidence:.2f} ({p.direction})")
